name: FE issue 作成
description: FE の issue テンプレート
title: "[工数] title"
projects: ["medpeer-dev/75"]
labels: ["FE"]
body:
  - type: textarea
    id: todo
    attributes:
      label: TODO
      value: |
        - [ ] TODO
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: 補足情報
    validations:
      required: false
  - type: textarea
    id: links
    attributes:
      label: 参照リンク
    validations:
      required: false
